### ISSUE TITLE
Is this still working? 

### ISSUE THREAD

**Issue by TiborUdvari** [MLH/google-docs-site-generator#1]
The demo page is giving a 404 😐

**Comment by nlaz** [comment]
Hey @TiborUdvari looks like the repo name was updated which broke the demo site.

Sadly, this project hasn't been maintained so I can't guarantee that it will work. In fact, I am going to deprecate this project and then delete the repository entirely. Please fork or clone the project if you would like to use it. I'll give this repository a week or so before closing it down. Lastly, I found [this resource](https://www.youdontneedwp.com/) in case it fits what you are looking for. I hope this makes sense and let me know if you have any other concerns. 🙂

**Comment by TiborUdvari** [comment]
Thanks, the ydnw seems like what I need.

**Comment by nlaz** [comment]
@TiborUdvari Great 👍 I'll kill this project since you found what you are looking for.
